version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4567-4584:4567-4584'
      - '8080:8080'
    environment:
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
